name: btpro_flutter_case
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Text
  auto_size_text: ^3.0.0

  # Network
  connectivity_plus: ^6.0.3

  # UI
  cached_network_image: ^3.3.1
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0

  # Responsive
  device_preview: ^1.2.0

  # HTTP
  dio: ^5.4.3+1
  equatable: ^2.0.5
  json_annotation: ^4.9.0

  #Firebase
  firebase_analytics: ^11.0.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  firebase_remote_config: ^5.0.1

  # Storage
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State Management
  get: ^4.6.6

  # Utility
  logger: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - .env
