// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy7i6c2vy5L7SGZsTUUpgDwmAyjTElftU',
    appId: '1:857590838321:web:7526e3d4fe5105b0855110',
    messagingSenderId: '857590838321',
    projectId: 'btpro-flutter-case-50832',
    authDomain: 'btpro-flutter-case-50832.firebaseapp.com',
    storageBucket: 'btpro-flutter-case-50832.appspot.com',
    measurementId: 'G-944BB4YVSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRHoWZVtdbf5QaEgRAONVtx7lQrEoTatE',
    appId: '1:857590838321:android:69f954de092730d6855110',
    messagingSenderId: '857590838321',
    projectId: 'btpro-flutter-case-50832',
    storageBucket: 'btpro-flutter-case-50832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyb6BnoR6F9IAHoeEuSYK3RuBdF69qY2s',
    appId: '1:857590838321:ios:207e3c3cef0cad1b855110',
    messagingSenderId: '857590838321',
    projectId: 'btpro-flutter-case-50832',
    storageBucket: 'btpro-flutter-case-50832.appspot.com',
    iosBundleId: 'com.example.btproFlutterCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyb6BnoR6F9IAHoeEuSYK3RuBdF69qY2s',
    appId: '1:857590838321:ios:207e3c3cef0cad1b855110',
    messagingSenderId: '857590838321',
    projectId: 'btpro-flutter-case-50832',
    storageBucket: 'btpro-flutter-case-50832.appspot.com',
    iosBundleId: 'com.example.btproFlutterCase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy7i6c2vy5L7SGZsTUUpgDwmAyjTElftU',
    appId: '1:857590838321:web:ee62acbeed77e09a855110',
    messagingSenderId: '857590838321',
    projectId: 'btpro-flutter-case-50832',
    authDomain: 'btpro-flutter-case-50832.firebaseapp.com',
    storageBucket: 'btpro-flutter-case-50832.appspot.com',
    measurementId: 'G-F6M14094F3',
  );
}
